name = "power_shutdown_confirm"
name_pretty = "Are you sure you want to shutdown?"
hide_from_providerlist = true

[[entries]]
text = "󰄬 Yes"
actions = { "confirm" = "notify-send 'Shutting down system...' && sleep 1 && systemctl poweroff" }

[[entries]]
text = "󰅖 No"
