name = "power_reboot_confirm"
name_pretty = "Are you sure you want to reboot?"
hide_from_providerlist = true

[[entries]]
text = "󰄬 Yes"
actions = { "confirm" = "notify-send 'Rebooting system...' && sleep 1 && systemctl reboot" }

[[entries]]
text = "󰅖 No"
