name = "screenshot_edit"
name_pretty = "Edit Screenshot"

[[entries]]
text = "󰩬 Area"
actions = { "edit" = "screenshot edit-area" }

[[entries]]
text = "󰹑 Fullscreen"
actions = { "edit" = "screenshot edit-output" }
