name = "screenshot_timer"
name_pretty = "Timer Screenshot"
hide_from_providerlist = true

[[entries]]
text = "󰔛 5s"
actions = { "timer" = "screenshot timer 5" }

[[entries]]
text = "󱑎 10s"
actions = { "timer" = "screenshot timer 10" }
